### ISSUE TITLE
"Backpack\Generators\Services\BackpackCommand contains 1 abstract method" after update

### ISSUE THREAD

**Issue by emogeekface** [Laravel-Backpack/Generators#172] opened 2023-01-19 14:21 UTC
# Bug report

After updating to v3.3.11 running any commands in terminal results in error:

```
Class Backpack\Generators\Services\BackpackCommand contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub)
````
### What I did:

ran `composer update`

### What I expected to happen:

package updated with no errors

### What happened:

encountered error above

### What I've already tried to fix it:

downgraded to 3.3.10 which fixes it

**Comment by pxpm** [comment] 2023-01-19 15:22
Hey @emogeekface 

So sorry we let this error slip 😢 

I've just tagged a new version with the hot-fix for this mistake. 

A `composer update backpack/generators` should get the fixed version for you. 

Cheers

**Comment by pxpm** [comment] 2023-01-19 18:12
closing, the issue is fixed and tagged! If anyone stumbles on this, please do a `composer update backpack/generators`

thanks again @emogeekface 🙏

**Closed by pxpm** 2023-01-19 18:12 UTC
