### ISSUE TITLE
Class 'Backpack\Generators\GeneratorsServiceProvider' not found

### ISSUE THREAD

**Issue by muflihfq** [Laravel-Backpack/Generators#129] opened 2022-03-11 08:32 UTC
# Bug report
 Class 'Backpack\Generators\GeneratorsServiceProvider' not found
### What I did:
Create a console command and downgrade php from 7.4 to 7.3 and executed the command in dockerfile
### What I expected to happen:
The command would work
### What happened:
it's error, Class 'Backpack\Generators\GeneratorsServiceProvider' not found in Application.php line 745
### What I've already tried to fix it:
execute composer install and composer update
### Backpack, Laravel, PHP, DB version:
4.1, 8.12, mysql 5.7

**Comment by promatik** [comment] 2022-08-21 22:16
Hi @muflihfq, sorry for the delay, can you please tell us if you still have this issue?

Can you tell how to reproduce this?
You said you tried to execute the command in a docker file, is this issue only happening in docker?

Is it possible that docker is running on production mode, installing production dependencies only and since `Backpack\Generators` is installed on dev it is not being installed on your docker?

**Comment by promatik** [comment] 2022-09-05 08:51
@muflihfq I'll close this one for now, I believe your issue was exactly the missing of the package in production.

If it's not, please reopen 👌

**Closed by promatik** 2022-09-05 08:51 UTC
Labels: Priority: MUST
